democelery/network/urls.py
from django.urls import path
from . import views

app_name = 'network'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create-subscriber/', views.CreateSubscriber.as_view(), name='create-subscriber'),
]

democelery/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('democelery.network.urls')),
]

democelery/network/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


class Subscriber(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.EmailField(verbose_name=_("Email"))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_("Fecha de creación"))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _("Suscriptor")
        verbose_name_plural = _("Suscriptores")


class Post(models.Model):
    title = models.CharField(verbose_name=_("Título"), max_length=500)
    content = models.TextField(verbose_name=_("Contenido"))
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("Creado por"))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_("Fecha de creación"))

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = _("Publicación")
        verbose_name_plural = _("Publicaciones")


class Log(models.Model):
    sent_to = models.CharField(max_length=1000, verbose_name=_("Enviado a"))
    data = models.TextField(verbose_name=_("Data"))
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.data

    class Meta:
        verbose_name = _("Log")
        verbose_name_plural = _("Logs")

democelery/security/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

democelery/network/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse
from .models import Post, Subscriber
from django.contrib import messages


class Index(ListView):
    model = Post
    paginate_by = 100
    template_name = "index.html"


class CreateSubscriber(CreateView):
    model = Subscriber
    fields = "__all__"
    success_url = "/"
    template_name = "index.html"

    def get_success_url(self):
        messages.success(self.request, '<b>¡Yei!</b> Ahora recibirás por email todas '
                                       'las actualizaciones de nuestro contenido :D')
        return reverse('network:index')

democelery/security/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

democelery/network/templates/base.html
{% load i18n static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Mi Blog</title>
    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">



    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static 'img/network.png' %}" sizes="180x180">
<link rel="icon" href="{% static 'img/network.png' %}" sizes="32x32" type="image/png">
<link rel="icon" href="{% static 'img/network.png' %}" sizes="16x16" type="image/png">
<link rel="manifest" href="{% static 'img/network.png' %}">
<link rel="mask-icon" href="{% static 'img/network.png' %}" color="#563d7c">
<link rel="icon" href="{% static 'img/network.png' %}">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/offcanvas.css' %}" rel="stylesheet">
  </head>
  <body class="bg-light">

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">

  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Social Tenant <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <a href="{% url 'logout' %}" class="btn btn-warning">{% trans 'Salir' %}</a>
    </form>
  </div>
</nav>

<main role="main" class="container">
  <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
    <img class="mr-3 rounded" src="{% static 'img/network.png' %}" alt="" width="48" height="48">
    <div class="lh-100">
      <h6 class="mb-0 text-white lh-100">{% trans 'Mi red social' %}</h6>
      <small>Bienvenido @{{ user.username }}</small>
    </div>
  </div>
    {% block content %}

    {% endblock content %}
</main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.6/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <script src="offcanvas.js"></script>
  </body>
</html>

democelery/network/templates/index.html
{% extends 'base.html' %}
{% load i18n static %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">{% trans 'Suscribirme al boletín de noticias' %}</h6>
        <form action="{% url 'network:create-subscriber' %}" method="post">
            {% csrf_token %}
            <div class="row g-3 mt-3 align-items-center">
                <div class="col-auto">
                    <label for="inputPassword6" class="col-form-label">{% trans "Nombre completo" %}</label>
                </div>
                <div class="col-auto">
                    <input type="text" id="id_full_name" name="full_name" class="form-control-sm"
                           aria-describedby="passwordHelpInline">
                </div>
                <div class="col-auto">
                    <label for="inputPassword6" class="col-form-label">{% trans "Correo electrónico" %}</label>
                </div>
                <div class="col-auto">
                    <input type="email" id="id_email" name="email" class="form-control-sm"
                           aria-describedby="passwordHelpInline">
                </div>
                <div class="col-auto">
                    <input type="submit" value="{% trans 'Registrarme' %}" class="btn btn-success btn-sm">
                </div>
            </div>
        </form>
    </div>
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">{% trans 'Nuestras publicaciones' %}</h6>
        {% if object_list %}
            {% for post in object_list %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#007bff"/>
                        <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">@{{ post.created_by.username }}</strong>
                        {{ post.content }}
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <div class="text-muted pt-3">
                <div class="alert alert-primary" role="alert">
                    {% trans '¡Ups! Aún no existen publicaciones' %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

democelery/security/templates/base_security.html
{% load i18n static widget_tweaks %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Signin Template · Bootstrap v4.6</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/sign-in/">



    <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
{#<link href="/docs/4.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">#}



    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.6/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.6/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.6/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.6/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.6/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.6/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.6/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
  {% block content %}
<form class="form-signin">
  <img class="mb-4" src="/docs/4.6/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2021</p>
</form>
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>